package Leetcode;

/**
 * @author : Sudeep Narkar
 * @since : 10/26/2020, Mon, 6:40 PM
 **/

//https://leetcode.com/problems/find-the-difference/
public class FindTheDifference {


    /**
     * You are given two strings s and t.
     * <p>
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     * <p>
     * Return the letter that was added to t.
     * <p>
     * <p>
     * <p>
     * Example 1:
     * <p>
     * Input: s = "abcd", t = "abcde"
     * Output: "e"
     * Explanation: 'e' is the letter that was added.
     * Example 2:
     * <p>
     * Input: s = "", t = "y"
     * Output: "y"
     * Example 3:
     * <p>
     * Input: s = "a", t = "aa"
     * Output: "a"
     * Example 4:
     * <p>
     * Input: s = "ae", t = "aea"
     * Output: "a"
     */

    public char findTheDifference(String s, String t) {

        if (s.equals("")) {
            return t.charAt(0);
        }
        int[] arr = new int[26];
        for (char c : s.toCharArray()) {
            arr[c - 'a']++;
        }

        //place holder for the letter addded
        char letterAdded = ' ';
        for (char c : t.toCharArray()) {
            arr[c - 'a']--;
            if (arr[c - 'a'] < 0) {
                letterAdded = c;
                break;
            }
        }
        return letterAdded;
    }
}